name: Cache Demo
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Prime cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ./
          key: cache-c76e2ac
          
      - name: prime-cache-c76e2ac
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
